# Generated by Django 4.2 on 2023-11-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0006_stock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
    ]
