# Generated by Django 4.2.7 on 2023-11-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0007_remove_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('Tools and Equipment', 'Tools and Equipment'), ('Safety Gear', 'Safety Gear'), ('Materials', 'Materials'), ('Site Supplies', 'Site Supplies'), ('Machinery Maintenance and Fuel', 'Machinery Maintenance and Fuel'), ('Office Supplies', 'Office Supplies')], max_length=50, null=True),
        ),
    ]
